### ISSUE TITLE
Fix runtimejs-kernels permission error

### ISSUE THREAD

**Issue by iefserge** [runtimejs/runtime-tools#5]
https://github.com/runtimejs/helloworld/issues/1

```
$ runtime-qemu ./initrd
shell.js: internal error
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/runtime-tools/runtimejs-kernels'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:799:18)
    at /usr/local/lib/node_modules/runtime-tools/node_modules/shelljs/src/mkdir.js:65:10
    at Array.forEach (native)
    at Object._mkdir (/usr/local/lib/node_modules/runtime-tools/node_modules/shelljs/src/mkdir.js:48:8)
    at Object.mkdir (/usr/local/lib/node_modules/runtime-tools/node_modules/shelljs/src/common.js:186:23)
    at module.exports (/usr/local/lib/node_modules/runtime-tools/get-prebuilt.js:8:11)
    at module.exports (/usr/local/lib/node_modules/runtime-tools/get-runtime.js:5:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/runtime-tools/bin/runtime-qemu.js:63:1)
    at Module._compile (module.js:434:26)
```

**Comment by facekapow** [comment]
Just opened #8.
